title: "Sarah Djebali"
author: "Sarah Djebali"
description: "Researcher in Bioinformatics and Genomics at INSERM"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "pub.md", title: "Publications"}
  - {file: "teach.md", title: "Supervision/Teaching"}
  - {file: "event.md", title: "Event organisation"}
  - {url: "https://web-genobioinfo.toulouse.inrae.fr/~sdjebali/CV_SD_English.pdf", title: "CV"}
  - {file: "misc.md", title: "Miscellaneous"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Mail", icon: envelope, url: "mailto:sarah.djebali@inserm.fr"}
  - {title: "Github", icon: github, url: "https://github.com/sdjebali"}
  - {title: "ORCID", icon: id-card, url: "https://orcid.org/0000-0002-0599-1267"}
  - {title: "LinkedIn", icon: linkedin, url: "https://www.linkedin.com/in/sarah-djebali-quelen-1544416/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
